language: node_js
node_js:
  - v12

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && coveralls < coverage/lcov.info

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: Skerwe/generator-njk-site
