language: node_js
node_js:
  - "12"
after_script: jest --coverage && coveralls < coverage/lcov.info
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: Skerwe/generator-njk-site
